enable-magisk-update = true
parallel-jobs = 1

patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

[YouTube]
build-mode = "module"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
build-mode = "module"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
dpi = "nodpi"
