enable-magisk-update = true
parallel-jobs = 1

patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

[YouTube]
build-mode = "module"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
build-mode = "module"
version = "8.10.52"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
